execute @s[scores={level=0}] ~~~ event entity @s ss:level1
execute @s[scores={level=1}] ~~~ event entity @s ss:level2
execute @s[scores={level=2}] ~~~ event entity @s ss:level3
execute @s[scores={level=3}] ~~~ event entity @s ss:level4
execute @s[scores={level=4}] ~~~ event entity @s ss:level5
execute @s[scores={level=5}] ~~~ event entity @s ss:level6
execute @s[scores={level=6}] ~~~ event entity @s ss:level7
execute @s[scores={level=7}] ~~~ event entity @s ss:level8
execute @s[scores={level=8}] ~~~ event entity @s ss:level9
execute @s[scores={level=9}] ~~~ event entity @s ss:level10
execute @s[scores={level=10}] ~~~ event entity @s ss:level11
execute @s[scores={level=11}] ~~~ event entity @s ss:level12
execute @s[scores={level=12}] ~~~ event entity @s ss:level13
execute @s[scores={level=13}] ~~~ event entity @s ss:level14
execute @s[scores={level=14}] ~~~ event entity @s ss:level15
execute @s[scores={level=15}] ~~~ event entity @s ss:level16
execute @s[scores={level=16}] ~~~ event entity @s ss:level17
execute @s[scores={level=17}] ~~~ event entity @s ss:level18
execute @s[scores={level=18}] ~~~ event entity @s ss:level19
execute @s[scores={level=19}] ~~~ event entity @s ss:level20
execute @s[scores={level=20}] ~~~ event entity @s ss:level21
execute @s[scores={level=21}] ~~~ event entity @s ss:level22
execute @s[scores={level=22}] ~~~ event entity @s ss:level23
execute @s[scores={level=23}] ~~~ event entity @s ss:level24
execute @s[scores={level=24}] ~~~ event entity @s ss:level25
execute @s[scores={level=25}] ~~~ event entity @s ss:level26
execute @s[scores={level=26}] ~~~ event entity @s ss:level27
execute @s[scores={level=27}] ~~~ event entity @s ss:level28
execute @s[scores={level=28}] ~~~ event entity @s ss:level29
execute @s[scores={level=29}] ~~~ event entity @s ss:level30
execute @s[scores={level=30}] ~~~ event entity @s ss:level31
execute @s[scores={level=31}] ~~~ event entity @s ss:level32
execute @s[scores={level=32}] ~~~ event entity @s ss:level33
execute @s[scores={level=33}] ~~~ event entity @s ss:level34
execute @s[scores={level=34}] ~~~ event entity @s ss:level35
execute @s[scores={level=35}] ~~~ event entity @s ss:level36
execute @s[scores={level=36}] ~~~ event entity @s ss:level37
execute @s[scores={level=37}] ~~~ event entity @s ss:level38
execute @s[scores={level=38}] ~~~ event entity @s ss:level39
execute @s[scores={level=39}] ~~~ event entity @s ss:level40
execute @s[scores={level=40}] ~~~ event entity @s ss:level41
execute @s[scores={level=41}] ~~~ event entity @s ss:level42
execute @s[scores={level=42}] ~~~ event entity @s ss:level43
execute @s[scores={level=43}] ~~~ event entity @s ss:level44
execute @s[scores={level=44}] ~~~ event entity @s ss:level45
execute @s[scores={level=45}] ~~~ event entity @s ss:level46
execute @s[scores={level=46}] ~~~ event entity @s ss:level47
execute @s[scores={level=47}] ~~~ event entity @s ss:level48
execute @s[scores={level=48}] ~~~ event entity @s ss:level49
execute @s[scores={level=49}] ~~~ event entity @s ss:level50
execute @s[scores={level=50}] ~~~ event entity @s ss:level51
execute @s[scores={level=51}] ~~~ event entity @s ss:level52
execute @s[scores={level=52}] ~~~ event entity @s ss:level53
execute @s[scores={level=53}] ~~~ event entity @s ss:level54
execute @s[scores={level=54}] ~~~ event entity @s ss:level55
execute @s[scores={level=55}] ~~~ event entity @s ss:level56
execute @s[scores={level=56}] ~~~ event entity @s ss:level57
execute @s[scores={level=57}] ~~~ event entity @s ss:level58
execute @s[scores={level=58}] ~~~ event entity @s ss:level59
execute @s[scores={level=59}] ~~~ event entity @s ss:level60
execute @s[scores={level=60}] ~~~ event entity @s ss:level61
execute @s[scores={level=61}] ~~~ event entity @s ss:level62
execute @s[scores={level=62}] ~~~ event entity @s ss:level63
execute @s[scores={level=63}] ~~~ event entity @s ss:level64
execute @s[scores={level=64}] ~~~ event entity @s ss:level65
execute @s[scores={level=65}] ~~~ event entity @s ss:level66
execute @s[scores={level=66}] ~~~ event entity @s ss:level67
execute @s[scores={level=67}] ~~~ event entity @s ss:level68
execute @s[scores={level=68}] ~~~ event entity @s ss:level69
execute @s[scores={level=69}] ~~~ event entity @s ss:level70
execute @s[scores={level=70}] ~~~ event entity @s ss:level71
execute @s[scores={level=71}] ~~~ event entity @s ss:level72
execute @s[scores={level=72}] ~~~ event entity @s ss:level73
execute @s[scores={level=73}] ~~~ event entity @s ss:level74
execute @s[scores={level=74}] ~~~ event entity @s ss:level75
execute @s[scores={level=75}] ~~~ event entity @s ss:level76
execute @s[scores={level=76}] ~~~ event entity @s ss:level77
execute @s[scores={level=77}] ~~~ event entity @s ss:level78
execute @s[scores={level=78}] ~~~ event entity @s ss:level79
execute @s[scores={level=79}] ~~~ event entity @s ss:level80
execute @s[scores={level=80}] ~~~ event entity @s ss:level81
execute @s[scores={level=81}] ~~~ event entity @s ss:level82
execute @s[scores={level=82}] ~~~ event entity @s ss:level83
execute @s[scores={level=83}] ~~~ event entity @s ss:level84
execute @s[scores={level=84}] ~~~ event entity @s ss:level85
execute @s[scores={level=85}] ~~~ event entity @s ss:level86
execute @s[scores={level=86}] ~~~ event entity @s ss:level87
execute @s[scores={level=87}] ~~~ event entity @s ss:level88
execute @s[scores={level=88}] ~~~ event entity @s ss:level89
execute @s[scores={level=89}] ~~~ event entity @s ss:level90
execute @s[scores={level=90}] ~~~ event entity @s ss:level91
execute @s[scores={level=91}] ~~~ event entity @s ss:level92
execute @s[scores={level=92}] ~~~ event entity @s ss:level93
execute @s[scores={level=93}] ~~~ event entity @s ss:level94
execute @s[scores={level=94}] ~~~ event entity @s ss:level95
execute @s[scores={level=95}] ~~~ event entity @s ss:level96
execute @s[scores={level=96}] ~~~ event entity @s ss:level97
execute @s[scores={level=97}] ~~~ event entity @s ss:level98
execute @s[scores={level=98}] ~~~ event entity @s ss:level99
execute @s[scores={level=99}] ~~~ event entity @s ss:level100
