# GUI Objectives
scoreboard objectives add selected dummy
scoreboard objectives add guiPage dummy
scoreboard objectives add guiScroll dummy
scoreboard objectives add guiinhand dummy
scoreboard objectives add guicrouch dummy
scoreboard objectives add combatlog dummy
scoreboard objectives add id dummy
scoreboard objectives add level dummy
scoreboard objectives add select dummy
scoreboard objectives add select dummy
scoreboard objectives add guicrouch dummy
scoreboard objectives add guiinhand dummy
scoreboard objectives add pokemon1 dummy
scoreboard objectives add pokemon2 dummy
scoreboard objectives add pokemon3 dummy
scoreboard objectives add pokemon4 dummy
scoreboard objectives add pokemon5 dummy
scoreboard objectives add pokemon6 dummy
scoreboard objectives add guislottrack dummy
scoreboard objectives add sendoutdis1 dummy
scoreboard objectives add sendoutdis2 dummy
scoreboard objectives add sendoutdis3 dummy
scoreboard objectives add sendoutdis4 dummy
scoreboard objectives add sendoutdis5 dummy
scoreboard objectives add sendoutdis6 dummy
scoreboard objectives add sendoutcooldown1 dummy
scoreboard objectives add sendoutcooldown2 dummy
scoreboard objectives add sendoutcooldown3 dummy
scoreboard objectives add sendoutcooldown4 dummy
scoreboard objectives add sendoutcooldown5 dummy
scoreboard objectives add sendoutcooldown6 dummy
scoreboard objectives add pokemondead1 dummy
scoreboard objectives add pokemondead2 dummy
scoreboard objectives add pokemondead3 dummy
scoreboard objectives add pokemondead4 dummy
scoreboard objectives add pokemondead5 dummy
scoreboard objectives add pokemondead6 dummy
scoreboard objectives add levelslot6 dummy
scoreboard objectives add levelslot5 dummy
scoreboard objectives add levelslot4 dummy
scoreboard objectives add levelslot3 dummy
scoreboard objectives add levelslot2 dummy
scoreboard objectives add levelslot1 dummy

# Run Time Objectives
scoreboard objectives add ticktimer dummy
scoreboard objectives add servertime dummy

