scoreboard players set @s[scores={guiScroll=5..}] guiScroll 0

execute @s[scores={pokemon1=0}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: none\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=0}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: none\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=0}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=0}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=0}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=1}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Growlithe\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=1}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=1}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=1}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=1}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=2}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Arcanine\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=2}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=2}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=2}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=2}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=3}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Krabby\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=3}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Krabby\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=3}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=3}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=3}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=4}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kingler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=4}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kingler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=4}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=4}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=4}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=5}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgey\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=5}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=5}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=5}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=5}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=6}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeotto\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=6}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=6}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=6}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=6}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=7}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeot\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=7}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=7}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=7}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=7}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=8}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Caterpie\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=8}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=8}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=8}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=8}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=9}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Metapod\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=9}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Metapod\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=9}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=9}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=9}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=10}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Butterfree\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=10}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=10}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=10}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=10}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=11}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Weedle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=11}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Weedle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=11}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=11}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=11}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=12}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kakuna\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=12}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=12}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=12}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=12}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=13}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Beedrill\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=13}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=13}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=13}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=13}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=14}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Shinx\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=14}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Shinx\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=14}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=14}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}

execute @s[scores={pokemon1=14}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
execute @s[scores={pokemon1=15}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxio\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=15}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxio\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=15}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=15}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=15}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=16}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxray\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=16}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxray\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=16}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=16}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=16}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=17}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gastly\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=17}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gastly\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=17}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=17}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=17}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=18}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Haunter\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=18}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Haunter\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=18}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=18}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=18}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=19}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gengar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=19}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gengar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=19}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=19}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=19}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=20}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Turtwig\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=20}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=20}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=20}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=20}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=21}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Grotle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=21}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Grotle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=21}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=21}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=21}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=22}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Torterra\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=22}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Torterra\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=22}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=22}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=22}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=23}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Eevee\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=23}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Eevee\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=23}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=23}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=23}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=24}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Flareon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=24}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Flareon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=24}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=24}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=24}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=25}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Jolteon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=25}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=25}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=25}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=25}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=26}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Vaporeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=26}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=26}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=26}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=26}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=27}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Leafeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=27}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=27}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=27}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=27}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=28}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Glaceon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=28}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=28}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=28}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=28}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=29}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Espeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=29}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Espeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=29}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=29}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=29}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=30}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Umbreon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=30}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=30}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=30}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=30}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=31}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Sylveon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=31}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=31}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=31}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=31}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=32}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Piplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=32}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Piplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=32}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=32}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=32}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=33}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Prinplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=33}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=33}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=33}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=33}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=34}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Empoleon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=34}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=34}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=34}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=34}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=35}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Chimchar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=35}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=35}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=35}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=35}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=36}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Monferno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=36}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Monferno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=36}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=36}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=36}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=37}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Infernape\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=37}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Infernape\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=37}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=37}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=37}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=38}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Onix\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=38}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Onix\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=38}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=38}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=38}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=39}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Psyduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=39}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=39}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=39}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=39}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=40}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=40}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=40}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=40}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=40}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}


execute @s[scores={pokemon1=41}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Skorupi\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=41}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=41}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=41}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=41}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=42}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Drapion\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=42}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Drapion\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=42}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=42}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=42}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=43}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bidoof\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=43}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=43}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=43}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=43}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=44}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bibarel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=44}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=44}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=44}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=44}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=45}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Mewtwo\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=45}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=45}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=45}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=45}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=46}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Articuno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=46}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Articuno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=46}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=46}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=46}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=47}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=47}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=47}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=47}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=47}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=48}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pikachu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=48}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=48}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=48}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=48}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=49}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Raichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=49}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Raichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=49}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=49}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=49}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=50}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Zubat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=50}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Zubat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=50}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=50}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=50}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=51}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=51}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=51}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=51}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=51}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=52}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Crowbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=52}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=52}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=52}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=52}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=53}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gible\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=53}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gible\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=53}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=53}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=53}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=54}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gabite\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=54}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gabite\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=54}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gabitee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=54}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=54}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=55}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Garchomp\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=55}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=55}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=55}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=55}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=56}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Riolu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=56}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Riolu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=56}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=56}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=56}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=57}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Lucario\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=57}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Lucario\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=57}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=57}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=57}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=58}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Buizel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=58}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Buizel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=58}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=58}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=58}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=59}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Floatzel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=59}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=59}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=59}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=59}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=60}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Geodude\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=60}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Geodude\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=60}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=60}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=60}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=61}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Graveler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=61}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Graveler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=61}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=61}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=61}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon1=62}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golem\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=62}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golem\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=62}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=62}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon1=62}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 1: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
