scoreboard players set @s[scores={guiScroll=5..}] guiScroll 0

execute @s[scores={pokemon2=0}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: none\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=0}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: none\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=0}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=0}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=0}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=1}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Growlithe\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=1}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=1}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=1}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=1}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=2}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Arcanine\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=2}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=2}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=2}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=2}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=3}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Krabby\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=3}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Krabby\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=3}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=3}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=3}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=4}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kingler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=4}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kingler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=4}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=4}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=4}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=5}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgey\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=5}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=5}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=5}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=5}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=6}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeotto\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=6}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=6}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=6}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=6}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=7}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeot\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=7}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=7}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=7}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=7}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=8}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Caterpie\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=8}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=8}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=8}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=8}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=9}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Metapod\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=9}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Metapod\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=9}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=9}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=9}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=10}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Butterfree\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=10}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=10}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=10}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=10}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=11}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Weedle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=11}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Weedle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=11}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=11}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=11}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=12}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kakuna\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=12}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=12}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=12}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=12}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=13}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Beedrill\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=13}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=13}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=13}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=13}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=14}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Shinx\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=14}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Shinx\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=14}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=14}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}

execute @s[scores={pokemon2=14}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
execute @s[scores={pokemon2=15}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxio\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=15}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxio\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=15}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=15}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=15}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=16}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxray\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=16}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxray\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=16}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=16}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=16}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=17}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gastly\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=17}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gastly\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=17}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=17}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=17}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=18}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Haunter\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=18}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Haunter\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=18}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=18}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=18}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=19}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gengar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=19}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gengar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=19}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=19}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=19}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=20}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Turtwig\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=20}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=20}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=20}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=20}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=21}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Grotle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=21}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Grotle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=21}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=21}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=21}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=22}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Torterra\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=22}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Torterra\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=22}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=22}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=22}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=23}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Eevee\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=23}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Eevee\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=23}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=23}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=23}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=24}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Flareon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=24}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Flareon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=24}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=24}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=24}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=25}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Jolteon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=25}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=25}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=25}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=25}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=26}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Vaporeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=26}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=26}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=26}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=26}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=27}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Leafeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=27}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=27}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=27}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=27}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=28}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Glaceon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=28}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=28}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=28}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=28}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=29}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Espeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=29}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Espeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=29}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=29}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=29}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=30}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Umbreon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=30}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=30}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=30}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=30}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=31}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Sylveon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=31}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=31}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=31}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=31}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=32}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Piplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=32}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Piplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=32}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=32}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=32}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=33}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Prinplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=33}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=33}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=33}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=33}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=34}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Empoleon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=34}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=34}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=34}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=34}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=35}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Chimchar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=35}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=35}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=35}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=35}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=36}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Monferno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=36}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Monferno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=36}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=36}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=36}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=37}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Infernape\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=37}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Infernape\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=37}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=37}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=37}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=38}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Onix\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=38}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Onix\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=38}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=38}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=38}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=39}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Psyduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=39}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=39}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=39}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=39}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=40}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=40}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=40}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=40}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=40}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=41}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Skorupi\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=41}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=41}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=41}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=41}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=42}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Drapion\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=42}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Drapion\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=42}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=42}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=42}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=43}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bidoof\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=43}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=43}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=43}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=43}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=44}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bibarel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=44}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=44}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=44}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=44}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=45}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Mewtwo\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=45}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=45}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=45}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=45}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=46}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Articuno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=46}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Articuno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=46}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=46}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=46}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=47}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=47}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=47}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=47}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=47}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=48}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pikachu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=48}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=48}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=48}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=48}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=49}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Raichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=49}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Raichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=49}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=49}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=49}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=50}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Zubat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=50}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Zubat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=50}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=50}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=50}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=51}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=51}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=51}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=51}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=51}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=52}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Crowbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=52}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=52}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=52}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=52}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=53}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gible\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=53}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gible\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=53}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=53}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=53}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=54}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gabite\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=54}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gabite\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=54}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gabitee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=54}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=54}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=55}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Garchomp\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=55}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=55}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=55}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=55}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=56}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Riolu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=56}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Riolu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=56}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=56}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=56}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=57}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Lucario\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=57}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Lucario\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=57}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=57}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=57}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=58}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Buizel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=58}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Buizel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=58}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=58}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=58}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=59}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Floatzel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=59}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=59}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=59}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=59}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=60}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Geodude\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=60}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Geodude\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=60}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=60}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=60}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=61}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Graveler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=61}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Graveler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=61}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=61}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=61}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon2=62}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golem\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=62}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golem\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=62}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=62}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon2=62}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 2: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
