scoreboard players set @s[scores={guiScroll=5..}] guiScroll 0

execute @s[scores={pokemon3=0}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: none\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=0}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: none\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=0}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=0}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=0}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=1}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Growlithe\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=1}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=1}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=1}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=1}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=2}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Arcanine\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=2}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=2}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=2}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=2}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=3}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Krabby\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=3}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Krabby\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=3}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=3}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=3}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=4}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kingler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=4}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kingler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=4}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=4}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=4}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=5}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgey\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=5}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=5}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=5}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=5}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=6}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeotto\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=6}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=6}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=6}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=6}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=7}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeot\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=7}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=7}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=7}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=7}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=8}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Caterpie\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=8}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=8}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=8}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=8}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=9}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Metapod\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=9}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Metapod\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=9}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=9}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=9}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=10}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Butterfree\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=10}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=10}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=10}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=10}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=11}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Weedle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=11}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Weedle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=11}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=11}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=11}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=12}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kakuna\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=12}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=12}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=12}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=12}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=13}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Beedrill\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=13}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=13}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=13}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=13}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=14}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Shinx\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=14}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Shinx\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=14}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=14}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}

execute @s[scores={pokemon3=14}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
execute @s[scores={pokemon3=15}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxio\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=15}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxio\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=15}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=15}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=15}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=16}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxray\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=16}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxray\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=16}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=16}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=16}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=17}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gastly\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=17}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gastly\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=17}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=17}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=17}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=18}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Haunter\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=18}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Haunter\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=18}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=18}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=18}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=19}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gengar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=19}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gengar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=19}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=19}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=19}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=20}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Turtwig\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=20}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=20}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=20}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=20}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=21}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Grotle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=21}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Grotle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=21}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=21}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=21}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=22}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Torterra\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=22}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Torterra\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=22}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=22}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=22}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=23}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Eevee\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=23}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Eevee\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=23}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=23}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=23}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=24}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Flareon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=24}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Flareon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=24}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=24}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=24}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=25}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Jolteon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=25}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=25}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=25}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=25}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=26}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Vaporeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=26}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=26}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=26}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=26}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=27}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Leafeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=27}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=27}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=27}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=27}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=28}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Glaceon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=28}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=28}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=28}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=28}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=29}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Espeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=29}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Espeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=29}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=29}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=29}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=30}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Umbreon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=30}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=30}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=30}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=30}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=31}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Sylveon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=31}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=31}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=31}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=31}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=32}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Piplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=32}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Piplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=32}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=32}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=32}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=33}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Prinplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=33}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=33}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=33}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=33}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=34}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Empoleon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=34}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=34}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=34}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=34}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=35}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Chimchar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=35}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=35}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=35}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=35}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=36}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Monferno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=36}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Monferno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=36}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=36}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=36}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=37}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Infernape\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=37}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Infernape\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=37}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=37}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=37}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=38}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Onix\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=38}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Onix\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=38}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=38}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=38}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=39}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Psyduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=39}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=39}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=39}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=39}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=40}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=40}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=40}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=40}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=40}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=41}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Skorupi\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=41}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=41}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=41}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=41}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=42}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Drapion\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=42}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Drapion\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=42}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=42}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=42}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=43}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bidoof\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=43}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=43}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=43}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=43}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=44}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bibarel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=44}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=44}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=44}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=44}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=45}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Mewtwo\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=45}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=45}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=45}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=45}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=46}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Articuno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=46}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Articuno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=46}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=46}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=46}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=47}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=47}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=47}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=47}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=47}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=48}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pikachu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=48}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=48}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=48}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=48}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=49}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Raichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=49}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Raichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=49}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=49}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=49}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=50}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Zubat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=50}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Zubat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=50}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=50}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=50}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=51}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=51}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=51}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=51}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=51}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=52}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Crowbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=52}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=52}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=52}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=52}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=53}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gible\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=53}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gible\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=53}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=53}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=53}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=54}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gabite\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=54}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gabite\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=54}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gabitee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=54}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=54}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=55}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Garchomp\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=55}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=55}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=55}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=55}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=56}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Riolu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=56}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Riolu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=56}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=56}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=56}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=57}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Lucario\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=57}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Lucario\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=57}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=57}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=57}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=58}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Buizel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=58}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Buizel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=58}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=58}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=58}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=59}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Floatzel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=59}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=59}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=59}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=59}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=60}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Geodude\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=60}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Geodude\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=60}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=60}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=60}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=61}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Graveler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=61}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Graveler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=61}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=61}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=61}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon3=62}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golem\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=62}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golem\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=62}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=62}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon3=62}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 3: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
