scoreboard players set @s[scores={guiScroll=5..}] guiScroll 0

execute @s[scores={pokemon4=0}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: none\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=0}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: none\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=0}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=0}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=0}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=1}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Growlithe\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=1}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=1}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=1}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=1}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=2}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Arcanine\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=2}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=2}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=2}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=2}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=3}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Krabby\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=3}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Krabby\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=3}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=3}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=3}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=4}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kingler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=4}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kingler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=4}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=4}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=4}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=5}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgey\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=5}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=5}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=5}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=5}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=6}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeotto\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=6}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=6}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=6}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=6}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=7}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeot\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=7}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=7}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=7}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=7}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}


execute @s[scores={pokemon4=8}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Caterpie\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=8}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=8}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=8}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=8}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=9}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Metapod\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=9}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Metapod\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=9}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=9}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=9}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=10}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Butterfree\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=10}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=10}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=10}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=10}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=11}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Weedle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=11}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Weedle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=11}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=11}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=11}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=12}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kakuna\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=12}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=12}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=12}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=12}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=13}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Beedrill\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=13}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=13}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=13}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=13}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=14}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Shinx\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=14}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Shinx\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=14}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=14}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}

execute @s[scores={pokemon4=14}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
execute @s[scores={pokemon4=15}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxio\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=15}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxio\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=15}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=15}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=15}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=16}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxray\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=16}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxray\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=16}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=16}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=16}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=17}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gastly\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=17}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gastly\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=17}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=17}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=17}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=18}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Haunter\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=18}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Haunter\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=18}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=18}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=18}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=19}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gengar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=19}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gengar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=19}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=19}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=19}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=20}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Turtwig\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=20}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=20}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=20}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=20}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=21}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Grotle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=21}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Grotle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=21}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=21}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=21}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=22}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Torterra\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=22}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Torterra\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=22}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=22}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=22}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=23}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Eevee\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=23}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Eevee\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=23}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=23}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=23}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=24}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Flareon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=24}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Flareon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=24}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=24}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=24}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=25}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Jolteon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=25}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=25}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=25}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=25}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=26}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Vaporeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=26}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=26}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=26}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=26}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=27}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Leafeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=27}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=27}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=27}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=27}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=28}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Glaceon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=28}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=28}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=28}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=28}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=29}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Espeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=29}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Espeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=29}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=29}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=29}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=30}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Umbreon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=30}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=30}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=30}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=30}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=31}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Sylveon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=31}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=31}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=31}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=31}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=32}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Piplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=32}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Piplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=32}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=32}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=32}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=33}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Prinplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=33}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=33}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=33}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=33}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=34}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Empoleon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=34}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=34}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=34}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=34}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=35}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Chimchar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=35}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=35}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=35}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=35}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=36}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Monferno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=36}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Monferno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=36}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=36}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=36}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=37}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Infernape\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=37}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Infernape\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=37}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=37}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=37}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=38}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Onix\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=38}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Onix\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=38}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=38}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=38}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=39}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Psyduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=39}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=39}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=39}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=39}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=40}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=40}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=40}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=40}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=40}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=41}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Skorupi\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=41}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=41}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=41}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=41}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=42}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Drapion\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=42}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Drapion\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=42}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=42}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=42}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=43}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bidoof\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=43}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=43}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=43}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=43}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=44}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bibarel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=44}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=44}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=44}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=44}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=45}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Mewtwo\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=45}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=45}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=45}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=45}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=46}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Articuno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=46}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Articuno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=46}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=46}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=46}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=47}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=47}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=47}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=47}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=47}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=48}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pikachu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=48}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=48}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=48}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=48}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=49}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Raichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=49}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Raichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=49}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=49}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=49}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=50}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Zubat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=50}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Zubat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=50}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=50}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=50}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=51}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=51}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=51}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=51}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=51}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=52}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Crowbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=52}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=52}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=52}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=52}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=53}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gible\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=53}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gible\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=53}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=53}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=53}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=54}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gabite\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=54}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gabite\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=54}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gabitee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=54}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=54}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=55}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Garchomp\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=55}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=55}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=55}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=55}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=56}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Riolu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=56}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Riolu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=56}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=56}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=56}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=57}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Lucario\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=57}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Lucario\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=57}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=57}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=57}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=58}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Buizel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=58}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Buizel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=58}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=58}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=58}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=59}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Floatzel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=59}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=59}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=59}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=59}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=60}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Geodude\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=60}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Geodude\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=60}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=60}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=60}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=61}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Graveler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=61}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Graveler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=61}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=61}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=61}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=62}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golem\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=62}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golem\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=62}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=62}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=62}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=63}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=63}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=63}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=63}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=63}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=64}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=64}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=64}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=64}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=64}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=65}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=65}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=65}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=65}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=65}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=66}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=66}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=66}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=66}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=66}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=67}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=67}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=67}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=67}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=67}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=68}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=68}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=68}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=68}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=68}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon4=69}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=69}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=69}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=69}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon4=69}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 4: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot4"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

