scoreboard players set @s[scores={guiScroll=5..}] guiScroll 0

execute @s[scores={pokemon6=0}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: none\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=0}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: none\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=0}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=0}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=0}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: none\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=1}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Growlithe\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=1}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=1}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=1}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=1}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Growlithe\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=2}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Arcanine\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=2}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=2}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=2}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=2}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Arcanine\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=3}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Krabby\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=3}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Krabby\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=3}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=3}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=3}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Krabby\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=4}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kingler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=4}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kingler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=4}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=4}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=4}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kingler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=5}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgey\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=5}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=5}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=5}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=5}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgey\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=6}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeotto\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=6}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=6}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=6}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=6}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeotto\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=7}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeot\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=7}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=7}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=7}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=7}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pidgeot\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=8}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Caterpie\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=8}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=8}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=8}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=8}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Caterpie\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=9}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Metapod\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=9}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Metapod\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=9}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=9}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=9}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Metapod\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=10}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Butterfree\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=10}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=10}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=10}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=10}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Butterfree\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=11}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Weedle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=11}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Weedle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=11}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=11}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=11}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Weedle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=12}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kakuna\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=12}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=12}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=12}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=12}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Kakuna\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=13}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Beedrill\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=13}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=13}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=13}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=13}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Beedrill\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=14}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Shinx\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=14}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Shinx\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=14}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=14}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}

execute @s[scores={pokemon6=14}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Shinx\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}
execute @s[scores={pokemon6=15}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxio\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=15}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxio\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=15}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=15}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=15}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxio\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=16}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxray\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=16}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxray\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=16}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=16}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=16}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Luxray\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=17}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gastly\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=17}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gastly\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=17}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=17}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=17}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gastly\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=18}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Haunter\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=18}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Haunter\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=18}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=18}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=18}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Haunter\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=19}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gengar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=19}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gengar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=19}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=19}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=19}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gengar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=20}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Turtwig\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=20}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=20}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=20}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=20}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Turtwig\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=21}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Grotle\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=21}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Grotle\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=21}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=21}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=21}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Grotle\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=22}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Torterra\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=22}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Torterra\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=22}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=22}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=22}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Torterra\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=23}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Eevee\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=23}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Eevee\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=23}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=23}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=23}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Eevee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=24}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Flareon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=24}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Flareon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=24}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=24}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=24}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Flareon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=25}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Jolteon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=25}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=25}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=25}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=25}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Jolteon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=26}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Vaporeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=26}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=26}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=26}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=26}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Vaporeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=27}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Leafeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=27}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=27}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=27}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=27}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Leafeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=28}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Glaceon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=28}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=28}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=28}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=28}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Glaceon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=29}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Espeon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=29}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Espeon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=29}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=29}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=29}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Espeon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=30}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Umbreon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=30}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=30}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=30}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=30}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Umbreon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=31}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Sylveon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=31}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=31}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=31}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=31}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Sylveon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=32}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Piplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=32}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Piplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=32}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=32}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=32}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Piplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=33}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Prinplup\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=33}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=33}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=33}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=33}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Prinplup\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=34}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Empoleon\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=34}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=34}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=34}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=34}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Empoleon\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=35}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Chimchar\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=35}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=35}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=35}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=35}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Chimchar\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=36}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Monferno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=36}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Monferno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=36}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=36}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=36}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Monferno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=37}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Infernape\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=37}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Infernape\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=37}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=37}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=37}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Infernape\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=38}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Onix\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=38}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Onix\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=38}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=38}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=38}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Onix\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=39}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Psyduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=39}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=39}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=39}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=39}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Psyduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=40}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golduck\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=40}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golduck\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=40}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=40}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=40}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golduck\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=41}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Skorupi\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=41}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=41}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=41}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=41}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Skorupi\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=42}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Drapion\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=42}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Drapion\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=42}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=42}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=42}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Drapion\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=43}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bidoof\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=43}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=43}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=43}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=43}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bidoof\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=44}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bibarel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=44}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=44}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=44}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=44}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Bibarel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=45}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Mewtwo\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=45}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=45}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=45}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=45}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Mewtwo\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=46}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Articuno\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=46}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Articuno\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=46}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=46}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=46}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Articuno\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=47}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=47}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=47}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=47}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=47}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=48}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pikachu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=48}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=48}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=48}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=48}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Pikachu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=49}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Raichu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=49}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Raichu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=49}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=49}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=49}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Raichu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=50}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Zubat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=50}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Zubat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=50}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=50}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=50}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Zubat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=51}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=51}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=51}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=51}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=51}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=52}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Crowbat\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=52}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=52}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=52}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=52}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Crowbat\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=53}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gible\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=53}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gible\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=53}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=53}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=53}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gible\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=54}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gabite\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=54}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gabite\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=54}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gabitee\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=54}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=54}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Gabite\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=55}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Garchomp\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=55}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=55}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=55}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=55}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Garchomp\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=56}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Riolu\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=56}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Riolu\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=56}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=56}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=56}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Riolu\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=57}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Lucario\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=57}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Lucario\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=57}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=57}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=57}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Lucario\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=58}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Buizel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=58}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Buizel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=58}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=58}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=58}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Buizel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=59}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Floatzel\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=59}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=59}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=59}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=59}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Floatzel\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=60}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Geodude\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=60}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Geodude\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=60}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=60}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=60}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Geodude\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=61}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Graveler\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=61}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Graveler\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=61}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=61}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=61}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Graveler\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=62}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golem\n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=62}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golem\n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=62}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=62}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=62}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Golem\n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=63}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=63}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=63}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=63}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=63}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machop \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=64}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=64}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=64}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=64}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=64}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machoke \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=65}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=65}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=65}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=65}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=65}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Machamp \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=66}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=66}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=66}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=66}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=66}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Murkrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=67}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=67}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=67}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=67}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=67}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Honchrow \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=68}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=68}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=68}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=68}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=68}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Aipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

execute @s[scores={pokemon6=69}] ~~~ titleraw @s[scores={guiScroll=0}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§c> §6Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=69}] ~~~ titleraw @s[scores={guiScroll=1}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§c> §6Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=69}] ~~~ titleraw @s[scores={guiScroll=2}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§c> §6Release Pokemon\n\n§aNext Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=69}] ~~~ titleraw @s[scores={guiScroll=3}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§c> §6Next Slot >\n§cBack\n\n§f-----------------"}]}
execute @s[scores={pokemon6=69}] ~~~ titleraw @s[scores={guiScroll=4}] actionbar {"rawtext":[{"text":"§f-----------------\n§cSlot 6: Ambipom \n§elvl: "},{"score":{"name": "@s","objective": "levelslot6"}},{"text":" \n§f-----------------\n§7Send Out Pokemon\n§7Return Pokemon\n§7Release Pokemon\n\n§aNext Slot >\n§c> §6Back\n\n§f-----------------"}]}

