# slot 6

execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=1..,pokemon6=0}] ~~~ scoreboard players set @p levelslot6 100


# Slot 5

execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=1..,pokemon5=0}] ~~~ scoreboard players set @p levelslot5 100

#level 4

execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=1..,pokemon4=0}] ~~~ scoreboard players set @p levelslot4 100

# level 3


execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=1..,pokemon3=0}] ~~~ scoreboard players set @p levelslot3 100

# level 2


execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=1..,pokemon2=0}] ~~~ scoreboard players set @p levelslot2 100

# level 1

execute @s[scores={level=0}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 0
execute @s[scores={level=1}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 1
execute @s[scores={level=2}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 2
execute @s[scores={level=3}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 3
execute @s[scores={level=4}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 4
execute @s[scores={level=5}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 5
execute @s[scores={level=6}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 6
execute @s[scores={level=7}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 7
execute @s[scores={level=8}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 8
execute @s[scores={level=9}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 9
execute @s[scores={level=10}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 10
execute @s[scores={level=11}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 11
execute @s[scores={level=12}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 12
execute @s[scores={level=13}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 13
execute @s[scores={level=14}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 14
execute @s[scores={level=15}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 15
execute @s[scores={level=16}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 16
execute @s[scores={level=17}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 17
execute @s[scores={level=18}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 18
execute @s[scores={level=19}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 19
execute @s[scores={level=20}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 20
execute @s[scores={level=21}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 21
execute @s[scores={level=22}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 22
execute @s[scores={level=23}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 23
execute @s[scores={level=24}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 24
execute @s[scores={level=25}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 25
execute @s[scores={level=26}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 26
execute @s[scores={level=27}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 27
execute @s[scores={level=28}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 28
execute @s[scores={level=29}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 29
execute @s[scores={level=30}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 30
execute @s[scores={level=31}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 31
execute @s[scores={level=32}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 32
execute @s[scores={level=33}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 33
execute @s[scores={level=34}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 34
execute @s[scores={level=35}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 35
execute @s[scores={level=36}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 36
execute @s[scores={level=37}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 37
execute @s[scores={level=38}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 38
execute @s[scores={level=39}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 39
execute @s[scores={level=40}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 40
execute @s[scores={level=41}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 41
execute @s[scores={level=42}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 42
execute @s[scores={level=43}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 43
execute @s[scores={level=44}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 44
execute @s[scores={level=45}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 45
execute @s[scores={level=46}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 46
execute @s[scores={level=47}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 47
execute @s[scores={level=48}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 48
execute @s[scores={level=49}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 49
execute @s[scores={level=50}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 50
execute @s[scores={level=51}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 51
execute @s[scores={level=52}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 52
execute @s[scores={level=53}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 53
execute @s[scores={level=54}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 54
execute @s[scores={level=55}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 55
execute @s[scores={level=56}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 56
execute @s[scores={level=57}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 57
execute @s[scores={level=58}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 58
execute @s[scores={level=59}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 59
execute @s[scores={level=60}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 60
execute @s[scores={level=61}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 61
execute @s[scores={level=62}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 62
execute @s[scores={level=63}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 63
execute @s[scores={level=64}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 64
execute @s[scores={level=65}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 65
execute @s[scores={level=66}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 66
execute @s[scores={level=67}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 67
execute @s[scores={level=68}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 68
execute @s[scores={level=69}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 69
execute @s[scores={level=70}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 70
execute @s[scores={level=71}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 71
execute @s[scores={level=72}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 72
execute @s[scores={level=73}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 73
execute @s[scores={level=74}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 74
execute @s[scores={level=75}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 75
execute @s[scores={level=76}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 76
execute @s[scores={level=77}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 77
execute @s[scores={level=78}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 78
execute @s[scores={level=79}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 79
execute @s[scores={level=80}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 80
execute @s[scores={level=81}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 81
execute @s[scores={level=82}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 82
execute @s[scores={level=83}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 83
execute @s[scores={level=84}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 84
execute @s[scores={level=85}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 85
execute @s[scores={level=86}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 86
execute @s[scores={level=87}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 87
execute @s[scores={level=88}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 88
execute @s[scores={level=89}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 89
execute @s[scores={level=90}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 90
execute @s[scores={level=91}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 91
execute @s[scores={level=92}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 92
execute @s[scores={level=93}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 93
execute @s[scores={level=94}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 94
execute @s[scores={level=95}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 95
execute @s[scores={level=96}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 96
execute @s[scores={level=97}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 97
execute @s[scores={level=98}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 98
execute @s[scores={level=99}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 99
execute @s[scores={level=100}] ~~~ execute @p[scores={pokemon1=0}] ~~~ scoreboard players set @p levelslot1 100
